using System;

namespace InventoryManagementSystem.Services
{
    public static class AppBranding
    {
        public const string DisplayName = "Glory Desk";
        public const string ShortName = "GloryDesk";
        public const string Tagline = "Stock, sales & accounts in one place";
        public const string CompanyName = "MT GLORY";
        public const string SupportEmail = "support@mtglory.com";
        public const string DocsUrl = "https://glorydesk.mtglory.com/docs";
        public const string LicenseUrl = "https://glorydesk.mtglory.com/activate";
        public const string WebsiteUrl = "https://glorydesk.mtglory.com";
        public const string DownloadUrl = "https://glorydesk.mtglory.com/download";
        /// <summary>GitHub repo used by Velopack for in-app updates (releases with RELEASES / nupkg assets).</summary>
        public const string GitHubReleasesRepoUrl = "https://github.com/mtgloryco/glorydesk";
        public const string PublicConfigUrl = "https://glorydesk.mtglory.com/api/public/config";

        public const string AppDataFolder = "GloryDesk";
        public const string LegacyAppDataFolder = "InventoryManagementSystem";
        public const string DocumentsFolder = "GloryDesk";

        public const string GeneratedByFooter = "Generated by Glory Desk";
        public const string CloudApiEnvVar = "GLORYDESK_CLOUD_API_URL";
        public const string LegacyCloudApiEnvVar = "IMS_CLOUD_API_URL";

        public static string ReleaseNotesUrlForVersion(string version)
        {
            var clean = (version ?? string.Empty).Trim().TrimStart('v', 'V');
            if (string.IsNullOrWhiteSpace(clean))
            {
                return $"{WebsiteUrl}/releases";
            }

            // User-facing notes on the Glory Desk site (matches /api/public/config releaseNotesBaseUrl)
            return $"{WebsiteUrl}/releases/{Uri.EscapeDataString(clean)}";
        }
    }
}
