namespace InventoryManagementSystem.Services
{
    public static class AppBranding
    {
        public const string DisplayName = "Glory Desk";
        public const string ShortName = "GloryDesk";
        public const string Tagline = "Stock, sales & accounts in one place";
        public const string CompanyName = "MT GLORY CO";
        public const string SupportEmail = "support@mtglory.com";
        public const string DocsUrl = "https://glorydesk.mtglory.com/docs";
        public const string LicenseUrl = "https://glorydesk.mtglory.com/activate";

        public const string AppDataFolder = "GloryDesk";
        public const string LegacyAppDataFolder = "InventoryManagementSystem";
        public const string DocumentsFolder = "GloryDesk";

        public const string GeneratedByFooter = "Generated by Glory Desk";
        public const string CloudApiEnvVar = "GLORYDESK_CLOUD_API_URL";
        public const string LegacyCloudApiEnvVar = "IMS_CLOUD_API_URL";
    }
}
